"""Configuration management — read/write config.yaml."""
from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

import yaml

from .scanner import ScanResult


@dataclass
class MetricConfig:
    """Configuration for a single metric within a goal."""
    name: str
    unit: str = ""
    healthy: float = 0
    warning: float = 0


@dataclass
class GoalConfig:
    """Configuration for a tracked goal."""
    id: str
    name: str
    builtin: bool = False
    metrics: list[MetricConfig] = field(default_factory=list)
    pipeline: str | None = None  # path to custom pipeline file


@dataclass
class AgentConfig:
    """Configuration for a known agent."""
    id: str
    name: str


@dataclass
class ProjectConfig:
    """Top-level project configuration."""
    openclaw_home: Path = field(default_factory=lambda: Path.home() / ".openclaw")
    agents: list[AgentConfig] = field(default_factory=list)
    goals: list[GoalConfig] = field(default_factory=list)
    db_path: Path = field(default_factory=lambda: Path("data/monitor.db"))

    @classmethod
    def load(cls, path: Path | str) -> "ProjectConfig":
        """Load configuration from a YAML file."""
        path = Path(path)
        with open(path, encoding="utf-8") as f:
            data = yaml.safe_load(f) or {}

        config = cls()
        config.openclaw_home = Path(data.get("openclaw_home", "~/.openclaw")).expanduser()
        raw_db = Path(data.get("db_path", "data/monitor.db"))
        if not raw_db.is_absolute():
            raw_db = path.parent / raw_db
        config.db_path = raw_db.resolve()

        for agent_data in data.get("agents", []):
            config.agents.append(AgentConfig(
                id=agent_data["id"],
                name=agent_data.get("name", agent_data["id"]),
            ))

        for goal_data in data.get("goals", []):
            metrics = []
            for m in goal_data.get("metrics", []):
                metrics.append(MetricConfig(
                    name=m["name"],
                    unit=m.get("unit", ""),
                    healthy=float(m.get("healthy", 0)),
                    warning=float(m.get("warning", 0)),
                ))
            config.goals.append(GoalConfig(
                id=goal_data["id"],
                name=goal_data.get("name", goal_data["id"]),
                builtin=goal_data.get("builtin", False),
                metrics=metrics,
                pipeline=goal_data.get("pipeline"),
            ))

        return config

    def save(self, path: Path | str) -> None:
        """Save configuration to a YAML file."""
        path = Path(path)
        path.parent.mkdir(parents=True, exist_ok=True)

        data: dict[str, Any] = {
            "openclaw_home": str(self.openclaw_home),
            "db_path": str(self.db_path),
            "agents": [
                {"id": a.id, "name": a.name}
                for a in self.agents
            ],
            "goals": [],
        }

        for goal in self.goals:
            goal_data: dict[str, Any] = {
                "id": goal.id,
                "name": goal.name,
                "builtin": goal.builtin,
                "metrics": [
                    {
                        "name": m.name,
                        "unit": m.unit,
                        "healthy": m.healthy,
                        "warning": m.warning,
                    }
                    for m in goal.metrics
                ],
            }
            if goal.pipeline:
                goal_data["pipeline"] = goal.pipeline
            data["goals"].append(goal_data)

        with open(path, "w", encoding="utf-8") as f:
            f.write("# OA — Operational Analytics Configuration\n")
            f.write("# Auto-generated by `oa init`. Edit freely.\n\n")
            yaml.dump(data, f, default_flow_style=False, sort_keys=False, allow_unicode=True)

    @classmethod
    def from_scan(cls, scan: ScanResult) -> "ProjectConfig":
        """Generate a default config from an OpenClaw scan result."""
        config = cls(openclaw_home=scan.openclaw_home)

        # Add detected agents
        for agent in scan.agents:
            config.agents.append(AgentConfig(id=agent.id, name=agent.name))

        # Built-in: G1 Cron Reliability
        config.goals.append(GoalConfig(
            id="cron_reliability",
            name="Cron Reliability",
            builtin=True,
            metrics=[
                MetricConfig(name="success_rate", unit="%", healthy=95, warning=80),
            ],
        ))

        # Built-in: G2 Team Health
        agent_count = len(scan.agents)
        healthy_threshold = max(1, int(agent_count * 0.75))
        warning_threshold = max(1, int(agent_count * 0.5))
        config.goals.append(GoalConfig(
            id="team_health",
            name="Team Health",
            builtin=True,
            metrics=[
                MetricConfig(
                    name="active_agent_count",
                    unit="count",
                    healthy=healthy_threshold,
                    warning=warning_threshold,
                ),
                MetricConfig(name="memory_discipline", unit="%", healthy=80, warning=50),
            ],
        ))

        return config
